apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    type: hyg
  namespace: hyg
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
