apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
  namespace: hyg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: hygieia-config
              key: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hygieia-secret
              key: mongouserpwd
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
        resources: {}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: pvc-mongo
status: {}
