apiVersion: v1
kind: PersistentVolume
metadata:
  name: hyg-logs
  labels:
    type: hyg-log
  namespace: hyg
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/log"
